dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.4.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
