dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^2.0.0
  http:
    path: ../../../toitlang/pkg-http
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  pixel_display:
    path: ../../../toitware/toit-pixel-display/
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.2.0
  solar_position:
    url: github.com/toitware/toit-solar-position
    version: ^0.0.3
  weather_icons:
    path: ../../../toitlang/toit-weather-icons/
