dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^2.0.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.4.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^2.5.0
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.2.0
  solar_position:
    url: github.com/toitware/toit-solar-position
    version: ^0.0.3
  weather_icons:
    url: github.com/toitlang/toit-weather-icons
    version: ^0.1.0
