dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.4
  solar_position:
    url: github.com/toitware/toit-solar-position
    version: ^0.0.3
